version: "3"
services:
  check:
    command:
      - "python"
      - "-u"
      - "check_token.py"
    build: .
    volumes:
      - .:/src
      - ~/.amplify:/src/src/token
  run-mnist:
    command:
      - "python"
      - "-u"
      - "mnist.py"
    build: .
    volumes:
      - .:/src
      - ~/.amplify:/src/src/token
  run-iris:
    command:
      - "python"
      - "-u"
      - "iris.py"
    build: .
    volumes:
      - .:/src
      - ~/.amplify:/src/src/token
